
spring:
  config:
    import:
      - configserver:${CONFIG_SERVER_URI:http://localhost:8888}
      - optional:file:.env[.properties]
  application:
    name: api-gateway

server:
  port: ${API_GATEWAY_PORT}