server:
  port: ${CART_PORT}


spring:
  application:
    name: cart-service

  jpa:
    hibernate:
      ddl-auto: update
    

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}