

spring:
  application:
    name: cart-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
