
spring:
  config:
    import:
      - configserver:${CONFIG_SERVER_URI:http://localhost:8888}
      - optional:file:.env[.properties]
  application:
    name: cart-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${CART_PORT}