

spring:
  application:
    name: config-server

  config:
    import: optional:file:.env[.properties]

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          search-paths: ${CONFIG_GIT_PATH}
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

server:
  port: ${CONFIG_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

