server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          search-paths: ${CONFIG_GIT_PATH:config-data}
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

